import type { CardDef } from "@multispire/shared";

// Ironclad card definitions. Pure functional game data: name, cost, and numeric
// effects. Values mirror Slay the Spire mechanics; tweak here to match StS2 as
// the import pipeline firms up. The `upgrade` field holds the upgraded delta.
//
// To add a card: append a CardDef here. The registry picks it up automatically.

export const IRONCLAD_CARDS: CardDef[] = [
  // ---- Starter ----
  {
    id: "strike_r",
    name: "Strike",
    character: "ironclad",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defend_r",
    name: "Defend",
    character: "ironclad",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 5 }],
    upgrade: { effects: [{ kind: "block", amount: 8 }] },
  },
  {
    id: "bash",
    name: "Bash",
    character: "ironclad",
    type: "attack",
    rarity: "basic",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
      ],
    },
  },

  // ---- A few commons ----
  {
    id: "anger",
    name: "Anger",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 6 },
      { kind: "addCardToPile", cardId: "anger", amount: 1, pile: "discard" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        { kind: "addCardToPile", cardId: "anger", amount: 1, pile: "discard" },
      ],
    },
  },
  {
    id: "cleave",
    name: "Cleave",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [{ kind: "damage", amount: 8 }],
    upgrade: { effects: [{ kind: "damage", amount: 11 }] },
  },
  {
    id: "clothesline",
    name: "Clothesline",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 12 },
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 14 },
        { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
      ],
    },
  },
  {
    id: "twin_strike",
    name: "Twin Strike",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 5, times: 2 }],
    upgrade: { effects: [{ kind: "damage", amount: 7, times: 2 }] },
  },
  {
    id: "pommel_strike",
    name: "Pommel Strike",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "draw", amount: 2 },
      ],
    },
  },
  {
    id: "iron_wave",
    name: "Iron Wave",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "block", amount: 5 },
      { kind: "damage", amount: 5 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 7 },
        { kind: "damage", amount: 7 },
      ],
    },
  },
  {
    id: "body_slam",
    name: "Body Slam",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damageEqualToBlock" }],
    upgrade: { cost: 0 },
  },
  {
    id: "shrug_it_off",
    name: "Shrug It Off",
    character: "ironclad",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 8 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 11 },
        { kind: "draw", amount: 1 },
      ],
    },
  },
  {
    id: "flex",
    name: "Flex",
    character: "ironclad",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    effects: [
      { kind: "applyPower", power: "strength", amount: 2, to: "self" },
      { kind: "applyPower", power: "strength_down", amount: 2, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "strength", amount: 4, to: "self" },
        { kind: "applyPower", power: "strength_down", amount: 4, to: "self" },
      ],
    },
  },

  // ---- A couple uncommons (powers) ----
  {
    id: "inflame",
    name: "Inflame",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "strength", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "strength", amount: 3, to: "self" }] },
  },
  {
    id: "metallicize",
    name: "Metallicize",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "metallicize", amount: 3, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "metallicize", amount: 4, to: "self" }] },
  },

  // ---- More commons ----
  {
    id: "clash",
    name: "Clash",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    // Playable only when every card in hand is an Attack (engine-enforced).
    requires: "all_attacks_in_hand",
    effects: [{ kind: "damage", amount: 14 }],
    upgrade: { effects: [{ kind: "damage", amount: 18 }] },
  },
  {
    id: "headbutt",
    name: "Headbutt",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "putDiscardOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "putDiscardOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "heavy_blade",
    name: "Heavy Blade",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    effects: [{ kind: "damage", amount: 14, strengthMul: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 14, strengthMul: 5 }] },
  },
  {
    id: "perfected_strike",
    name: "Perfected Strike",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    // Deal 6, +2 damage for every card containing "Strike" across your deck.
    effects: [{ kind: "damage", amount: 6, perStrike: 2 }],
    upgrade: { effects: [{ kind: "damage", amount: 6, perStrike: 3 }] },
  },
  {
    id: "sword_boomerang",
    name: "Sword Boomerang",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // In 1v1 the "random enemy" target is just your opponent.
    effects: [{ kind: "damage", amount: 3, times: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 3, times: 4 }] },
  },
  {
    id: "thunderclap",
    name: "Thunderclap",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 4 },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 7 },
        { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
      ],
    },
  },
  {
    id: "true_grit",
    name: "True Grit",
    character: "ironclad",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 7 },
      { kind: "exhaustRandom", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 9 },
        { kind: "exhaustRandom", amount: 1 },
      ],
    },
  },
  {
    id: "warcry",
    name: "Warcry",
    character: "ironclad",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    exhaust: true,
    effects: [
      { kind: "draw", amount: 1 },
      { kind: "putHandOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "draw", amount: 2 },
        { kind: "putHandOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "wild_strike",
    name: "Wild Strike",
    character: "ironclad",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 12 },
      { kind: "addCardToPile", cardId: "wound", amount: 1, pile: "draw" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 17 },
        { kind: "addCardToPile", cardId: "wound", amount: 1, pile: "draw" },
      ],
    },
  },

  // ---- Uncommons ----
  {
    id: "battle_trance",
    name: "Battle Trance",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [
      { kind: "draw", amount: 3 },
      { kind: "applyPower", power: "no_draw", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "draw", amount: 4 },
        { kind: "applyPower", power: "no_draw", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "blood_for_blood",
    name: "Blood for Blood",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 4,
    target: "enemy",
    dynamicCost: "hp_loss",
    effects: [{ kind: "damage", amount: 18 }],
    upgrade: { cost: 3, effects: [{ kind: "damage", amount: 22 }] },
  },
  {
    id: "bloodletting",
    name: "Bloodletting",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [
      { kind: "loseHp", amount: 3 },
      { kind: "gainEnergy", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "loseHp", amount: 3 },
        { kind: "gainEnergy", amount: 3 },
      ],
    },
  },
  {
    id: "burning_pact",
    name: "Burning Pact",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "exhaustChosen", amount: 1 },
      { kind: "draw", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "exhaustChosen", amount: 1 },
        { kind: "draw", amount: 3 },
      ],
    },
  },
  {
    id: "carnage",
    name: "Carnage",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    ethereal: true,
    effects: [{ kind: "damage", amount: 20 }],
    upgrade: { effects: [{ kind: "damage", amount: 28 }] },
  },
  {
    id: "disarm",
    name: "Disarm",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    exhaust: true,
    effects: [{ kind: "applyPower", power: "strength", amount: -2, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "strength", amount: -3, to: "enemy" }] },
  },
  {
    id: "dropkick",
    name: "Dropkick",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 5 },
      {
        kind: "ifTargetHasPower",
        power: "vulnerable",
        then: [
          { kind: "gainEnergy", amount: 1 },
          { kind: "draw", amount: 1 },
        ],
      },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        {
          kind: "ifTargetHasPower",
          power: "vulnerable",
          then: [
            { kind: "gainEnergy", amount: 1 },
            { kind: "draw", amount: 1 },
          ],
        },
      ],
    },
  },
  {
    id: "entrench",
    name: "Entrench",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [{ kind: "doubleBlock" }],
    upgrade: { cost: 1, effects: [{ kind: "doubleBlock" }] },
  },
  {
    id: "flame_barrier",
    name: "Flame Barrier",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    // Thorns lasts only until end of turn: the matching thorns_down removes it
    // during end-of-turn upkeep (after this turn's attacks have resolved).
    effects: [
      { kind: "block", amount: 12 },
      { kind: "applyPower", power: "thorns", amount: 4, to: "self" },
      { kind: "applyPower", power: "thorns_down", amount: 4, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 16 },
        { kind: "applyPower", power: "thorns", amount: 6, to: "self" },
        { kind: "applyPower", power: "thorns_down", amount: 6, to: "self" },
      ],
    },
  },
  {
    id: "ghostly_armor",
    name: "Ghostly Armor",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    ethereal: true,
    effects: [{ kind: "block", amount: 10 }],
    upgrade: { effects: [{ kind: "block", amount: 13 }] },
  },
  {
    id: "hemokinesis",
    name: "Hemokinesis",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "loseHp", amount: 2 },
      { kind: "damage", amount: 15 },
    ],
    upgrade: {
      effects: [
        { kind: "loseHp", amount: 2 },
        { kind: "damage", amount: 20 },
      ],
    },
  },
  {
    id: "intimidate",
    name: "Intimidate",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "all_enemies",
    exhaust: true,
    effects: [{ kind: "applyPower", power: "weak", amount: 1, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "weak", amount: 2, to: "enemy" }] },
  },
  {
    id: "power_through",
    name: "Power Through",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 15 },
      { kind: "addCardToPile", cardId: "wound", amount: 2, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 20 },
        { kind: "addCardToPile", cardId: "wound", amount: 2, pile: "hand" },
      ],
    },
  },
  {
    id: "pummel",
    name: "Pummel",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    exhaust: true,
    effects: [{ kind: "damage", amount: 2, times: 4 }],
    upgrade: { effects: [{ kind: "damage", amount: 2, times: 5 }] },
  },
  {
    id: "rage",
    name: "Rage",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [{ kind: "applyPower", power: "rage", amount: 3, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "rage", amount: 5, to: "self" }] },
  },
  {
    id: "rampage",
    name: "Rampage",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // +5 damage every time this card is played this combat (per-instance counter).
    effects: [{ kind: "damage", amount: 8, rampage: 5 }],
    upgrade: { effects: [{ kind: "damage", amount: 8, rampage: 8 }] },
  },
  {
    id: "reckless_charge",
    name: "Reckless Charge",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "addCardToPile", cardId: "dazed", amount: 1, pile: "draw" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "addCardToPile", cardId: "dazed", amount: 1, pile: "draw" },
      ],
    },
  },
  {
    id: "searing_blow",
    name: "Searing Blow",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    // StS lets this be upgraded repeatedly; we model a single upgrade tier.
    effects: [{ kind: "damage", amount: 12 }],
    upgrade: { effects: [{ kind: "damage", amount: 16 }] },
  },
  {
    id: "seeing_red",
    name: "Seeing Red",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    exhaust: true,
    effects: [{ kind: "gainEnergy", amount: 2 }],
    upgrade: { cost: 0, effects: [{ kind: "gainEnergy", amount: 2 }] },
  },
  {
    id: "sentinel",
    name: "Sentinel",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // If this card is Exhausted (by another effect), gain Energy.
    effects: [{ kind: "block", amount: 5 }],
    onExhaust: [{ kind: "gainEnergy", amount: 2 }],
    upgrade: {
      effects: [{ kind: "block", amount: 8 }],
      onExhaust: [{ kind: "gainEnergy", amount: 3 }],
    },
  },
  {
    id: "sever_soul",
    name: "Sever Soul",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "exhaustNonAttacks" },
      { kind: "damage", amount: 16 },
    ],
    upgrade: {
      effects: [
        { kind: "exhaustNonAttacks" },
        { kind: "damage", amount: 20 },
      ],
    },
  },
  {
    id: "shockwave",
    name: "Shockwave",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "all_enemies",
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "weak", amount: 5, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 5, to: "enemy" },
      ],
    },
  },
  {
    id: "spot_weakness",
    name: "Spot Weakness",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // PvP stand-in for "if the enemy intends to attack": gain Strength only if an
    // opponent has already queued an attack on you this turn.
    effects: [{ kind: "ifIncomingAttack", then: [{ kind: "applyPower", power: "strength", amount: 3, to: "self" }] }],
    upgrade: {
      effects: [{ kind: "ifIncomingAttack", then: [{ kind: "applyPower", power: "strength", amount: 4, to: "self" }] }],
    },
  },
  {
    id: "uppercut",
    name: "Uppercut",
    character: "ironclad",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 13 },
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 13 },
        { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
      ],
    },
  },

  {
    id: "second_wind",
    name: "Second Wind",
    character: "ironclad",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "exhaustNonAttacks", blockPerCard: 5 }],
    upgrade: { effects: [{ kind: "exhaustNonAttacks", blockPerCard: 7 }] },
  },
  {
    id: "feel_no_pain",
    name: "Feel No Pain",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "feel_no_pain", amount: 3, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "feel_no_pain", amount: 4, to: "self" }] },
  },
  {
    id: "dark_embrace",
    name: "Dark Embrace",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [{ kind: "applyPower", power: "dark_embrace", amount: 1, to: "self" }],
    upgrade: { cost: 1, effects: [{ kind: "applyPower", power: "dark_embrace", amount: 1, to: "self" }] },
  },
  {
    id: "berserk",
    name: "Berserk",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "self" },
      { kind: "applyPower", power: "berserk", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "vulnerable", amount: 1, to: "self" },
        { kind: "applyPower", power: "berserk", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "rupture",
    name: "Rupture",
    character: "ironclad",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "rupture", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "rupture", amount: 2, to: "self" }] },
  },

  // ---- Rares ----
  {
    id: "brutality",
    name: "Brutality",
    character: "ironclad",
    type: "power",
    rarity: "rare",
    cost: 0,
    target: "self",
    // Upgrade in StS adds Innate (draw at combat start), which we don't model, so
    // this is left non-upgradable rather than faked.
    effects: [{ kind: "applyPower", power: "brutality", amount: 1, to: "self" }],
  },
  {
    id: "fiend_fire",
    name: "Fiend Fire",
    character: "ironclad",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    exhaust: true,
    effects: [{ kind: "exhaustHandForDamage", perCard: 7 }],
    upgrade: { effects: [{ kind: "exhaustHandForDamage", perCard: 10 }] },
  },
  {
    id: "barricade",
    name: "Barricade",
    character: "ironclad",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    effects: [{ kind: "applyPower", power: "barricade", amount: 1, to: "self" }],
    upgrade: { cost: 2, effects: [{ kind: "applyPower", power: "barricade", amount: 1, to: "self" }] },
  },
  {
    id: "bludgeon",
    name: "Bludgeon",
    character: "ironclad",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "enemy",
    effects: [{ kind: "damage", amount: 32 }],
    upgrade: { effects: [{ kind: "damage", amount: 42 }] },
  },
  {
    id: "demon_form",
    name: "Demon Form",
    character: "ironclad",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    effects: [{ kind: "applyPower", power: "demon_form", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "demon_form", amount: 3, to: "self" }] },
  },
  {
    id: "feed",
    name: "Feed",
    character: "ironclad",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    exhaust: true,
    effects: [{ kind: "damage", amount: 10, maxHpOnKill: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 12, maxHpOnKill: 4 }] },
  },
  {
    id: "immolate",
    name: "Immolate",
    character: "ironclad",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 21 },
      { kind: "addCardToPile", cardId: "burn", amount: 1, pile: "discard" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 28 },
        { kind: "addCardToPile", cardId: "burn", amount: 1, pile: "discard" },
      ],
    },
  },
  {
    id: "impervious",
    name: "Impervious",
    character: "ironclad",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "self",
    exhaust: true,
    effects: [{ kind: "block", amount: 30 }],
    upgrade: { effects: [{ kind: "block", amount: 40 }] },
  },
  {
    id: "limit_break",
    name: "Limit Break",
    character: "ironclad",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    exhaust: true,
    effects: [{ kind: "doubleStrength" }],
    // Upgrade removes Exhaust.
    upgrade: { exhaust: false, effects: [{ kind: "doubleStrength" }] },
  },
  {
    id: "offering",
    name: "Offering",
    character: "ironclad",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "self",
    exhaust: true,
    effects: [
      { kind: "loseHp", amount: 6 },
      { kind: "gainEnergy", amount: 2 },
      { kind: "draw", amount: 3 },
    ],
    upgrade: {
      effects: [
        { kind: "loseHp", amount: 6 },
        { kind: "gainEnergy", amount: 2 },
        { kind: "draw", amount: 5 },
      ],
    },
  },
  {
    id: "reaper",
    name: "Reaper",
    character: "ironclad",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all_enemies",
    exhaust: true,
    effects: [{ kind: "damage", amount: 4, lifesteal: true }],
    upgrade: { effects: [{ kind: "damage", amount: 5, lifesteal: true }] },
  },

  // ---- Status / curse examples (so decks importing them don't crash) ----
  {
    id: "wound",
    name: "Wound",
    character: "neutral",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    effects: [],
    unplayable: true,
  },
  {
    id: "dazed",
    name: "Dazed",
    character: "neutral",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    // Ethereal: if still in hand at end of turn it exhausts instead of staying.
    ethereal: true,
    effects: [],
    unplayable: true,
  },
  {
    id: "burn",
    name: "Burn",
    character: "neutral",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    // Unplayable; deals 2 damage at end of turn for each Burn in hand (engine upkeep).
    effects: [],
    unplayable: true,
  },
  {
    id: "void",
    name: "Void",
    character: "neutral",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    // Approximated: the "lose 1 energy when drawn" rider is not modeled.
    effects: [],
    unplayable: true,
  },
  {
    id: "slimed",
    name: "Slimed",
    character: "neutral",
    type: "status",
    rarity: "special",
    cost: 1,
    target: "none",
    // Playable to clear it out; Exhausts with no effect.
    exhaust: true,
    effects: [],
  },
];
