import type { CardDef } from "@multispire/shared";

// Necrobinder card definitions (Slay the Spire 2). Pure functional game data.
// Signature systems: Osty (a summon with its own Max HP that strikes for you and
// can be sacrificed), Doom (at end of turn, if a target's Doom >= its HP it dies),
// and heavy Ethereal use. This is a first pass; Soul cards and the Osty-attack /
// doom-scaling riders are still to come (see docs/STS2_AUDIT.md, task #43).

export const NECROBINDER_CARDS: CardDef[] = [
  // ---- Starter ----
  {
    id: "strike_n",
    name: "Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defend_n",
    name: "Defend",
    character: "necrobinder",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 5 }],
    upgrade: { effects: [{ kind: "block", amount: 8 }] },
  },
  {
    id: "bodyguard",
    name: "Bodyguard",
    character: "necrobinder",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "summon", amount: 5 }],
    upgrade: { effects: [{ kind: "summon", amount: 7 }] },
  },
  {
    id: "unleash",
    name: "Unleash",
    character: "necrobinder",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    // Osty deals 6 (9) damage plus his current HP.
    effects: [{ kind: "ostyDamage", amount: 6, perOstyCurrentHp: 1 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 9, perOstyCurrentHp: 1 }] },
  },

  // ---- Commons ----
  {
    id: "poke",
    name: "Poke",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "ostyDamage", amount: 6 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 9 }] },
  },
  {
    id: "blight_strike",
    name: "Blight Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Deal damage and apply Doom equal to the damage.
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "applyPower", power: "doom", amount: 8, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "applyPower", power: "doom", amount: 10, to: "enemy" },
      ],
    },
  },
  {
    id: "scourge",
    name: "Scourge",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "applyPower", power: "doom", amount: 13, to: "enemy" },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "doom", amount: 16, to: "enemy" },
        { kind: "draw", amount: 2 },
      ],
    },
  },
  {
    id: "negative_pulse",
    name: "Negative Pulse",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "block", amount: 5 },
      { kind: "applyPower", power: "doom", amount: 7, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 6 },
        { kind: "applyPower", power: "doom", amount: 11, to: "enemy" },
      ],
    },
  },
  {
    id: "grave_warden",
    name: "Grave Warden",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 8 },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 11 },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
      ],
    },
  },
  {
    id: "defile",
    name: "Defile",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [{ kind: "damage", amount: 13 }],
    upgrade: { effects: [{ kind: "damage", amount: 17 }] },
  },
  {
    id: "fear",
    name: "Fear",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "reap",
    name: "Reap",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 3,
    target: "enemy",
    retain: true,
    effects: [{ kind: "damage", amount: 27 }],
    upgrade: { effects: [{ kind: "damage", amount: 33 }] },
  },
  {
    id: "sow",
    name: "Sow",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    retain: true,
    effects: [{ kind: "damage", amount: 8 }],
    upgrade: { effects: [{ kind: "damage", amount: 11 }] },
  },

  // ---- Uncommons ----
  {
    id: "deathbringer",
    name: "Deathbringer",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "all_enemies",
    effects: [
      { kind: "applyPower", power: "doom", amount: 21, to: "enemy" },
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "doom", amount: 26, to: "enemy" },
        { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "no_escape",
    name: "No Escape",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Apply Doom, +5 more for every 10 Doom the target already has.
    effects: [{ kind: "applyDoom", amount: 10, perExistingTen: 5 }],
    upgrade: { effects: [{ kind: "applyDoom", amount: 15, perExistingTen: 5 }] },
  },
  {
    id: "putrefy",
    name: "Putrefy",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
      ],
    },
  },
  {
    id: "bury",
    name: "Bury",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 4,
    target: "enemy",
    effects: [{ kind: "damage", amount: 52 }],
    upgrade: { effects: [{ kind: "damage", amount: 63 }] },
  },

  // ---- Rares ----
  {
    id: "sacrifice",
    name: "Sacrifice",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    retain: true,
    effects: [{ kind: "sacrificeOsty", blockPerMaxHp: 2 }],
    upgrade: { effects: [{ kind: "sacrificeOsty", blockPerMaxHp: 2 }] },
  },
  {
    id: "reanimate",
    name: "Reanimate",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 3,
    target: "self",
    exhaust: true,
    effects: [{ kind: "summon", amount: 20 }],
    upgrade: { effects: [{ kind: "summon", amount: 25 }] },
  },
  {
    id: "end_of_days",
    name: "End of Days",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 3,
    target: "all_enemies",
    // Doom's own end-of-turn rule handles the kill if Doom >= HP.
    effects: [{ kind: "applyPower", power: "doom", amount: 29, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "doom", amount: 37, to: "enemy" }] },
  },
  {
    id: "graveblast",
    name: "Graveblast",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Deal damage and retrieve a card from your discard pile (to the top of draw).
    effects: [
      { kind: "damage", amount: 4 },
      { kind: "putDiscardOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 6 },
        { kind: "putDiscardOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "spur",
    name: "Spur",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    retain: true,
    effects: [
      { kind: "summon", amount: 3 },
      { kind: "healOsty", amount: 5 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 5 },
        { kind: "healOsty", amount: 7 },
      ],
    },
  },
  {
    id: "debilitate",
    name: "Debilitate",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Weak and Vulnerable are twice as effective on the enemy for the next 3 (4) turns.
    effects: [
      { kind: "damage", amount: 10 },
      { kind: "applyPower", power: "exposed", amount: 3, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "applyPower", power: "exposed", amount: 4, to: "enemy" },
      ],
    },
  },
  {
    id: "shroud",
    name: "Shroud",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "shroud", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "shroud", amount: 3, to: "self" }] },
  },
  {
    id: "spirit_of_ash",
    name: "Spirit of Ash",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "spirit_of_ash", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "spirit_of_ash", amount: 5, to: "self" }] },
  },
  {
    id: "wisp",
    name: "Wisp",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    retain: true,
    exhaust: true,
    effects: [{ kind: "gainEnergy", amount: 1 }],
    upgrade: { effects: [{ kind: "gainEnergy", amount: 1 }] },
  },
  {
    id: "pull_aggro",
    name: "Pull Aggro",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 2,
    target: "self",
    effects: [
      { kind: "summon", amount: 4 },
      { kind: "block", amount: 7 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 5 },
        { kind: "block", amount: 9 },
      ],
    },
  },
  {
    id: "sculpting_strike",
    name: "Sculpting Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Deal damage, then add Ethereal to a chosen card in your hand.
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "makeEtherealChosen", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "makeEtherealChosen", amount: 1 },
      ],
    },
  },
  {
    id: "cleanse",
    name: "Cleanse",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "summon", amount: 3 },
      { kind: "exhaustFromDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 5 },
        { kind: "exhaustFromDraw", amount: 1 },
      ],
    },
  },
  {
    id: "invoke",
    name: "Invoke",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    // StS2 delays the summon to next turn; modeled as an immediate Summon here.
    effects: [
      { kind: "summon", amount: 2 },
      { kind: "nextTurnBonus", energy: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 3 },
        { kind: "nextTurnBonus", energy: 1 },
      ],
    },
  },
  {
    id: "seance",
    name: "Seance",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    ethereal: true,
    // Transform a card in your draw pile into a Soul.
    effects: [{ kind: "transformDraw", into: "soul", amount: 1 }],
    upgrade: { effects: [{ kind: "transformDraw", into: "soul", amount: 1 }] },
  },
  {
    id: "glimpse_beyond",
    name: "Glimpse Beyond",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    exhaust: true,
    // StS2 gives every player Souls; in a duel you add them to your own hand.
    effects: [{ kind: "addCardToPile", cardId: "soul", amount: 3, pile: "hand" }],
    upgrade: { effects: [{ kind: "addCardToPile", cardId: "soul", amount: 4, pile: "hand" }] },
  },
  {
    id: "reave",
    name: "Reave",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 11 },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
      ],
    },
  },
  {
    id: "afterlife",
    name: "Afterlife",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    exhaust: true,
    effects: [{ kind: "summon", amount: 6 }],
    upgrade: { effects: [{ kind: "summon", amount: 9 }] },
  },
  {
    id: "oblivion",
    name: "Oblivion",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "all_enemies",
    // Apply Doom equal to the number of cards you've played this turn.
    effects: [{ kind: "applyDoom", amount: 0, perCardThisTurn: 3 }],
    upgrade: { effects: [{ kind: "applyDoom", amount: 0, perCardThisTurn: 4 }] },
  },
  {
    id: "misery",
    name: "Misery",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 0,
    target: "enemy",
    // Deal damage, then apply this enemy's debuffs to all other enemies.
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "spreadDebuffs" },
    ],
    upgrade: {
      retain: true,
      effects: [
        { kind: "damage", amount: 9 },
        { kind: "spreadDebuffs" },
      ],
    },
  },
  {
    id: "defy",
    name: "Defy",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [
      { kind: "block", amount: 6 },
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 9 },
        { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      ],
    },
  },
  {
    id: "deaths_door",
    name: "Death's Door",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // Doubled if you applied Doom this turn.
    effects: [
      { kind: "block", amount: 6 },
      { kind: "ifDoomAppliedThisTurn", then: [{ kind: "block", amount: 6 }] },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 7 },
        { kind: "ifDoomAppliedThisTurn", then: [{ kind: "block", amount: 7 }] },
      ],
    },
  },
  {
    id: "enfeebling_touch",
    name: "Enfeebling Touch",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [{ kind: "applyPower", power: "strength", amount: -8, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "strength", amount: -11, to: "enemy" }] },
  },
  {
    id: "drain_power",
    name: "Drain Power",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 10 }],
    upgrade: { effects: [{ kind: "damage", amount: 12 }] },
  },
  {
    id: "capture_spirit",
    name: "Capture Spirit",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // The enemy loses HP directly (ignores Block); you gain Souls.
    effects: [
      { kind: "loseHpTarget", amount: 3 },
      { kind: "addCardToPile", cardId: "soul", amount: 3, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "loseHpTarget", amount: 4 },
        { kind: "addCardToPile", cardId: "soul", amount: 4, pile: "hand" },
      ],
    },
  },
  {
    id: "severance",
    name: "Severance",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    // Add a Soul to your hand, draw pile, and discard pile.
    effects: [
      { kind: "damage", amount: 13 },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "draw" },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "discard" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 18 },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "draw" },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "discard" },
      ],
    },
  },
  {
    id: "parse",
    name: "Parse",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    ethereal: true,
    effects: [{ kind: "draw", amount: 3 }],
    upgrade: { effects: [{ kind: "draw", amount: 4 }] },
  },
  {
    id: "delay",
    name: "Delay",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [
      { kind: "block", amount: 11 },
      { kind: "nextTurnBonus", energy: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 13 },
        { kind: "nextTurnBonus", energy: 1 },
      ],
    },
  },
  {
    id: "dredge",
    name: "Dredge",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    retain: true,
    exhaust: true,
    // Retrieve cards from your discard pile (to the top of your draw pile).
    effects: [{ kind: "putDiscardOnDraw", amount: 3 }],
    upgrade: { effects: [{ kind: "putDiscardOnDraw", amount: 3 }] },
  },
  {
    id: "neurosurge",
    name: "Neurosurge",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 0,
    target: "self",
    // Gain Energy and draw, but Doom yourself.
    effects: [
      { kind: "gainEnergy", amount: 3 },
      { kind: "draw", amount: 2 },
      { kind: "applyPower", power: "doom", amount: 3, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "gainEnergy", amount: 4 },
        { kind: "draw", amount: 2 },
        { kind: "applyPower", power: "doom", amount: 3, to: "self" },
      ],
    },
  },
  {
    id: "eradicate",
    name: "Eradicate",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: "X",
    target: "enemy",
    retain: true,
    // Deal 11/14 damage X times (X = energy spent).
    effects: [{ kind: "damagePerX", amount: 11 }],
    upgrade: { effects: [{ kind: "damagePerX", amount: 14 }] },
  },
  {
    id: "times_up",
    name: "Time's Up",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    retain: true,
    exhaust: true,
    effects: [{ kind: "damageEqualToTargetDoom" }],
    upgrade: { effects: [{ kind: "damageEqualToTargetDoom" }] },
  },
  {
    id: "soul_storm",
    name: "Soul Storm",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 9, perSoulInExhaust: 2 }],
    upgrade: { effects: [{ kind: "damage", amount: 9, perSoulInExhaust: 3 }] },
  },
  {
    id: "snap",
    name: "Snap",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Osty deals damage; add Retain to a chosen card in your hand.
    effects: [
      { kind: "ostyDamage", amount: 7 },
      { kind: "makeRetainChosen", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "ostyDamage", amount: 10 },
        { kind: "makeRetainChosen", amount: 1 },
      ],
    },
  },
  {
    id: "fetch",
    name: "Fetch",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "ostyDamageFirstDraw", amount: 3, draw: 1 }],
    upgrade: { effects: [{ kind: "ostyDamageFirstDraw", amount: 6, draw: 1 }] },
  },
  {
    id: "right_hand_hand",
    name: "Right Hand Hand",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    // Osty deals damage; returns from your discard pile whenever Osty attacks.
    effects: [{ kind: "ostyDamage", amount: 4 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 6 }] },
  },
  {
    id: "protector",
    name: "Protector",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Osty deals 10 (15) damage plus his Max HP.
    effects: [{ kind: "ostyDamage", amount: 10, perOstyMaxHp: 1 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 15, perOstyMaxHp: 1 }] },
  },
  {
    id: "sic_em",
    name: "Sic 'Em",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "ostyDamage", amount: 5 },
      { kind: "summon", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "ostyDamage", amount: 6 },
        { kind: "summon", amount: 3 },
      ],
    },
  },
  {
    id: "high_five",
    name: "High Five",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "ostyDamage", amount: 11 },
      { kind: "applyPowerAll", power: "vulnerable", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "ostyDamage", amount: 13 },
        { kind: "applyPowerAll", power: "vulnerable", amount: 3 },
      ],
    },
  },
  {
    id: "flatten",
    name: "Flatten",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    // Costs 0 if Osty already attacked this turn.
    dynamicCost: "osty_attacked",
    effects: [{ kind: "ostyDamage", amount: 12 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 16 }] },
  },
  {
    id: "rattle",
    name: "Rattle",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Osty deals 7 (9) damage, hitting again for each Osty attack this turn.
    effects: [{ kind: "ostyDamage", amount: 7, hitsPerOstyAttack: true }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 9, hitsPerOstyAttack: true }] },
  },
  {
    id: "squeeze",
    name: "Squeeze",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "enemy",
    // Osty deals 25 (30) damage, +5 (6) per other Osty attack this turn.
    effects: [{ kind: "ostyDamage", amount: 25, perOstyAttackThisTurn: 5 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 30, perOstyAttackThisTurn: 6 }] },
  },
  {
    id: "bone_shards",
    name: "Bone Shards",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "all_enemies",
    // Osty hits all enemies and gains Block, then dies.
    effects: [
      { kind: "ostyDamage", amount: 9 },
      { kind: "block", amount: 9 },
      { kind: "sacrificeOsty", blockPerMaxHp: 0 },
    ],
    upgrade: {
      effects: [
        { kind: "ostyDamage", amount: 12 },
        { kind: "block", amount: 12 },
        { kind: "sacrificeOsty", blockPerMaxHp: 0 },
      ],
    },
  },
  {
    id: "undeath",
    name: "Undeath",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "self",
    // Gain Block; add a copy of a card in your hand to your discard pile.
    effects: [
      { kind: "block", amount: 7 },
      { kind: "duplicateChosen", amount: 1, toPile: "discard" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 9 },
        { kind: "duplicateChosen", amount: 1, toPile: "discard" },
      ],
    },
  },
  {
    id: "dirge",
    name: "Dirge",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: "X",
    target: "self",
    // Summon 3 (4) X times; add X Souls.
    effects: [
      { kind: "summonPerX", amount: 3 },
      { kind: "addCardPerX", cardId: "soul" },
    ],
    upgrade: {
      effects: [
        { kind: "summonPerX", amount: 4 },
        { kind: "addCardPerX", cardId: "soul" },
      ],
    },
  },
  {
    id: "melancholy",
    name: "Melancholy",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 3,
    target: "self",
    // Costs 1 less for each enemy that has died this combat.
    dynamicCost: "deaths",
    effects: [{ kind: "block", amount: 13 }],
    upgrade: { effects: [{ kind: "block", amount: 17 }] },
  },
  {
    id: "hang",
    name: "Hang",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    // Deal damage (scaled by this enemy's Hang), then double its Hang.
    effects: [
      { kind: "damage", amount: 10, hangScaled: true },
      { kind: "doubleHang" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 13, hangScaled: true },
        { kind: "doubleHang" },
      ],
    },
  },
  {
    id: "veilpiercer",
    name: "Veilpiercer",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 10 },
      { kind: "nextEtherealFree" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 13 },
        { kind: "nextEtherealFree" },
      ],
    },
  },
  {
    id: "call_of_the_void",
    name: "Call of the Void",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    innate: true,
    // At the start of each turn, add a random Ethereal card to your hand.
    effects: [{ kind: "applyPower", power: "call_of_the_void", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "call_of_the_void", amount: 1, to: "self" }] },
  },
  {
    id: "shared_fate",
    name: "Shared Fate",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "enemy",
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "strength", amount: -2, to: "self" },
      { kind: "applyPower", power: "strength", amount: -2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "strength", amount: -2, to: "self" },
        { kind: "applyPower", power: "strength", amount: -3, to: "enemy" },
      ],
    },
  },
  {
    id: "death_march",
    name: "Death March",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 8, perCardDrawnThisTurn: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 9, perCardDrawnThisTurn: 4 }] },
  },
  {
    id: "pull_from_below",
    name: "Pull from Below",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 0, perEtherealPlayedThisTurn: 5 }],
    upgrade: { effects: [{ kind: "damage", amount: 0, perEtherealPlayedThisTurn: 7 }] },
  },
  {
    id: "borrowed_time",
    name: "Borrowed Time",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // Gain Energy now; your cards cost 1 more for the rest of this turn.
    effects: [
      { kind: "gainEnergy", amount: 4 },
      { kind: "applyPower", power: "cost_up", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "gainEnergy", amount: 6 },
        { kind: "applyPower", power: "cost_up", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "eidolon",
    name: "Eidolon",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "self",
    exhaust: true,
    // Exhaust your hand; if you exhausted 9+ cards, gain 1 Intangible.
    effects: [{ kind: "exhaustHandForIntangible", threshold: 9, intangible: 1 }],
    upgrade: { cost: 1, effects: [{ kind: "exhaustHandForIntangible", threshold: 9, intangible: 1 }] },
  },
  {
    id: "banshees_cry",
    name: "Banshee's Cry",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 9,
    target: "all_enemies",
    // Costs 2 less for each Ethereal card in your hand.
    dynamicCost: "ethereal_in_hand",
    effects: [{ kind: "damage", amount: 33 }],
    upgrade: { effects: [{ kind: "damage", amount: 40 }] },
  },
  {
    id: "danse_macabre",
    name: "Danse Macabre",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "danse_macabre", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "danse_macabre", amount: 6, to: "self" }] },
  },
  {
    id: "pagestorm",
    name: "Pagestorm",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "pagestorm", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "pagestorm", amount: 1, to: "self" }] },
  },
  {
    id: "sleight_of_flesh",
    name: "Sleight of Flesh",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [{ kind: "applyPower", power: "sleight_of_flesh", amount: 9, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "sleight_of_flesh", amount: 13, to: "self" }] },
  },
  {
    id: "friendship",
    name: "Friendship",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // Lose Strength now; gain 1 Energy at the start of each turn.
    effects: [
      { kind: "applyPower", power: "strength", amount: -2, to: "self" },
      { kind: "applyPower", power: "friendship", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "strength", amount: -1, to: "self" },
        { kind: "applyPower", power: "friendship", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "demesne",
    name: "Demesne",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    ethereal: true,
    // At the start of each turn, gain 1 Energy and draw 1 extra card.
    effects: [{ kind: "applyPower", power: "demesne", amount: 1, to: "self" }],
    upgrade: { cost: 2, effects: [{ kind: "applyPower", power: "demesne", amount: 1, to: "self" }] },
  },
  {
    id: "lethality",
    name: "Lethality",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    ethereal: true,
    // Your first Attack each turn deals 50% (75%) more damage.
    effects: [{ kind: "applyPower", power: "lethality", amount: 50, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "lethality", amount: 75, to: "self" }] },
  },
  {
    id: "countdown",
    name: "Countdown",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "countdown", amount: 6, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "countdown", amount: 9, to: "self" }] },
  },
  {
    id: "devour_life",
    name: "Devour Life",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "devour_life", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "devour_life", amount: 2, to: "self" }] },
  },
  {
    id: "haunt",
    name: "Haunt",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "haunt", amount: 6, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "haunt", amount: 8, to: "self" }] },
  },
  {
    id: "calcify",
    name: "Calcify",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // Osty's attacks deal additional damage.
    effects: [{ kind: "applyPower", power: "calcify", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "calcify", amount: 6, to: "self" }] },
  },
  {
    id: "reaper_form",
    name: "Reaper Form",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    retain: true,
    effects: [{ kind: "applyPower", power: "reaper_form", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "reaper_form", amount: 1, to: "self" }] },
  },
];
