import type { CardDef } from "@multispire/shared";

// Necrobinder card definitions (Slay the Spire 2). Pure functional game data.
// Signature systems: Osty (a summon with its own Max HP that strikes for you and
// can be sacrificed), Doom (at end of turn, if a target's Doom >= its HP it dies),
// and heavy Ethereal use. This is a first pass; Soul cards and the Osty-attack /
// doom-scaling riders are still to come (see docs/STS2_AUDIT.md, task #43).

export const NECROBINDER_CARDS: CardDef[] = [
  // ---- Starter ----
  {
    id: "strike_n",
    name: "Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defend_n",
    name: "Defend",
    character: "necrobinder",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 5 }],
    upgrade: { effects: [{ kind: "block", amount: 8 }] },
  },
  {
    id: "bodyguard",
    name: "Bodyguard",
    character: "necrobinder",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "summon", amount: 5 }],
    upgrade: { effects: [{ kind: "summon", amount: 7 }] },
  },
  {
    id: "unleash",
    name: "Unleash",
    character: "necrobinder",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "ostyDamage", amount: 6 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 9 }] },
  },

  // ---- Commons ----
  {
    id: "poke",
    name: "Poke",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "ostyDamage", amount: 6 }],
    upgrade: { effects: [{ kind: "ostyDamage", amount: 9 }] },
  },
  {
    id: "blight_strike",
    name: "Blight Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Deal damage and apply Doom equal to the damage.
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "applyPower", power: "doom", amount: 8, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "applyPower", power: "doom", amount: 10, to: "enemy" },
      ],
    },
  },
  {
    id: "scourge",
    name: "Scourge",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "applyPower", power: "doom", amount: 13, to: "enemy" },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "doom", amount: 16, to: "enemy" },
        { kind: "draw", amount: 2 },
      ],
    },
  },
  {
    id: "negative_pulse",
    name: "Negative Pulse",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "block", amount: 5 },
      { kind: "applyPower", power: "doom", amount: 7, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 6 },
        { kind: "applyPower", power: "doom", amount: 11, to: "enemy" },
      ],
    },
  },
  {
    id: "grave_warden",
    name: "Grave Warden",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 8 },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 11 },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
      ],
    },
  },
  {
    id: "defile",
    name: "Defile",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [{ kind: "damage", amount: 13 }],
    upgrade: { effects: [{ kind: "damage", amount: 17 }] },
  },
  {
    id: "fear",
    name: "Fear",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "reap",
    name: "Reap",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 3,
    target: "enemy",
    retain: true,
    effects: [{ kind: "damage", amount: 27 }],
    upgrade: { effects: [{ kind: "damage", amount: 33 }] },
  },
  {
    id: "sow",
    name: "Sow",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    retain: true,
    effects: [{ kind: "damage", amount: 8 }],
    upgrade: { effects: [{ kind: "damage", amount: 11 }] },
  },

  // ---- Uncommons ----
  {
    id: "deathbringer",
    name: "Deathbringer",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "all_enemies",
    effects: [
      { kind: "applyPower", power: "doom", amount: 21, to: "enemy" },
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "doom", amount: 26, to: "enemy" },
        { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "no_escape",
    name: "No Escape",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Apply Doom, +5 more for every 10 Doom the target already has.
    effects: [{ kind: "applyDoom", amount: 10, perExistingTen: 5 }],
    upgrade: { effects: [{ kind: "applyDoom", amount: 15, perExistingTen: 5 }] },
  },
  {
    id: "putrefy",
    name: "Putrefy",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
      ],
    },
  },
  {
    id: "bury",
    name: "Bury",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 4,
    target: "enemy",
    effects: [{ kind: "damage", amount: 52 }],
    upgrade: { effects: [{ kind: "damage", amount: 63 }] },
  },

  // ---- Rares ----
  {
    id: "sacrifice",
    name: "Sacrifice",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    retain: true,
    effects: [{ kind: "sacrificeOsty", blockPerMaxHp: 2 }],
    upgrade: { effects: [{ kind: "sacrificeOsty", blockPerMaxHp: 2 }] },
  },
  {
    id: "reanimate",
    name: "Reanimate",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 3,
    target: "self",
    exhaust: true,
    effects: [{ kind: "summon", amount: 20 }],
    upgrade: { effects: [{ kind: "summon", amount: 25 }] },
  },
  {
    id: "end_of_days",
    name: "End of Days",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 3,
    target: "all_enemies",
    // Doom's own end-of-turn rule handles the kill if Doom >= HP.
    effects: [{ kind: "applyPower", power: "doom", amount: 29, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "doom", amount: 37, to: "enemy" }] },
  },
  {
    id: "graveblast",
    name: "Graveblast",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // Deal damage and retrieve a card from your discard pile (to the top of draw).
    effects: [
      { kind: "damage", amount: 4 },
      { kind: "putDiscardOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 6 },
        { kind: "putDiscardOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "spur",
    name: "Spur",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    retain: true,
    // StS2 also heals Osty; the heal rider is a later pass.
    effects: [{ kind: "summon", amount: 3 }],
    upgrade: { effects: [{ kind: "summon", amount: 5 }] },
  },
  {
    id: "debilitate",
    name: "Debilitate",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // StS2: debuffs are twice as effective on the target; approximated here as a
    // Vulnerable application alongside the hit.
    effects: [
      { kind: "damage", amount: 10 },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
      ],
    },
  },
  {
    id: "shroud",
    name: "Shroud",
    character: "necrobinder",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "shroud", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "shroud", amount: 3, to: "self" }] },
  },
  {
    id: "spirit_of_ash",
    name: "Spirit of Ash",
    character: "necrobinder",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "spirit_of_ash", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "spirit_of_ash", amount: 5, to: "self" }] },
  },
  {
    id: "wisp",
    name: "Wisp",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    retain: true,
    exhaust: true,
    effects: [{ kind: "gainEnergy", amount: 1 }],
    upgrade: { effects: [{ kind: "gainEnergy", amount: 1 }] },
  },
  {
    id: "pull_aggro",
    name: "Pull Aggro",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 2,
    target: "self",
    effects: [
      { kind: "summon", amount: 4 },
      { kind: "block", amount: 7 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 5 },
        { kind: "block", amount: 9 },
      ],
    },
  },
  {
    id: "sculpting_strike",
    name: "Sculpting Strike",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    // StS2 also adds Ethereal to a card in hand; that rider is a later pass.
    effects: [{ kind: "damage", amount: 9 }],
    upgrade: { effects: [{ kind: "damage", amount: 12 }] },
  },
  {
    id: "cleanse",
    name: "Cleanse",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // StS2 also exhausts a card from the draw pile; that rider is a later pass.
    effects: [{ kind: "summon", amount: 3 }],
    upgrade: { effects: [{ kind: "summon", amount: 5 }] },
  },
  {
    id: "invoke",
    name: "Invoke",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    // StS2 delays the summon to next turn; modeled as an immediate Summon here.
    effects: [
      { kind: "summon", amount: 2 },
      { kind: "nextTurnBonus", energy: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "summon", amount: 3 },
        { kind: "nextTurnBonus", energy: 1 },
      ],
    },
  },
  {
    id: "seance",
    name: "Seance",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    ethereal: true,
    // Transform a card in your draw pile into a Soul.
    effects: [{ kind: "transformDraw", into: "soul", amount: 1 }],
    upgrade: { effects: [{ kind: "transformDraw", into: "soul", amount: 1 }] },
  },
  {
    id: "glimpse_beyond",
    name: "Glimpse Beyond",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    exhaust: true,
    // StS2 gives every player Souls; in a duel you add them to your own hand.
    effects: [{ kind: "addCardToPile", cardId: "soul", amount: 3, pile: "hand" }],
    upgrade: { effects: [{ kind: "addCardToPile", cardId: "soul", amount: 4, pile: "hand" }] },
  },
  {
    id: "oblivion",
    name: "Oblivion",
    character: "necrobinder",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "all_enemies",
    // Apply Doom equal to the number of cards you've played this turn.
    effects: [{ kind: "applyDoom", amount: 0, perCardThisTurn: 3 }],
    upgrade: { effects: [{ kind: "applyDoom", amount: 0, perCardThisTurn: 4 }] },
  },
  {
    id: "misery",
    name: "Misery",
    character: "necrobinder",
    type: "attack",
    rarity: "rare",
    cost: 0,
    target: "enemy",
    retain: true,
    // StS2 also spreads the enemy's debuffs; that rider is a later pass.
    effects: [{ kind: "damage", amount: 7 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defy",
    name: "Defy",
    character: "necrobinder",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [
      { kind: "block", amount: 6 },
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 9 },
        { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      ],
    },
  },
  {
    id: "deaths_door",
    name: "Death's Door",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    // StS2 doubles the Block if you applied Doom this turn; rider is a later pass.
    effects: [{ kind: "block", amount: 6 }],
    upgrade: { effects: [{ kind: "block", amount: 7 }] },
  },
  {
    id: "enfeebling_touch",
    name: "Enfeebling Touch",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    ethereal: true,
    effects: [{ kind: "applyPower", power: "strength", amount: -8, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "strength", amount: -11, to: "enemy" }] },
  },
  {
    id: "drain_power",
    name: "Drain Power",
    character: "necrobinder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 10 }],
    upgrade: { effects: [{ kind: "damage", amount: 12 }] },
  },
  {
    id: "capture_spirit",
    name: "Capture Spirit",
    character: "necrobinder",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // StS2 makes the enemy lose HP directly; approximated as damage here.
    effects: [
      { kind: "damage", amount: 3 },
      { kind: "addCardToPile", cardId: "soul", amount: 3, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 4 },
        { kind: "addCardToPile", cardId: "soul", amount: 4, pile: "hand" },
      ],
    },
  },
  {
    id: "severance",
    name: "Severance",
    character: "necrobinder",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    // Add a Soul to your hand, draw pile, and discard pile.
    effects: [
      { kind: "damage", amount: 13 },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "draw" },
      { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "discard" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 18 },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "hand" },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "draw" },
        { kind: "addCardToPile", cardId: "soul", amount: 1, pile: "discard" },
      ],
    },
  },
];
