import type { CardDef } from "@multispire/shared";

// Colorless / neutral cards. Pure functional game data. Only cards whose effects
// map cleanly onto the engine's primitives are included; approximations are noted.

export const NEUTRAL_CARDS: CardDef[] = [
  {
    id: "bandage_up",
    name: "Bandage Up",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    exhaust: true,
    effects: [{ kind: "heal", amount: 4 }],
    upgrade: { effects: [{ kind: "heal", amount: 6 }] },
  },
  {
    id: "bite",
    name: "Bite",
    character: "neutral",
    type: "attack",
    rarity: "special",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "heal", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        { kind: "heal", amount: 3 },
      ],
    },
  },
  {
    id: "blind",
    name: "Blind",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "applyPower", power: "weak", amount: 2, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "weak", amount: 2, to: "enemy" }] },
  },
  {
    id: "dark_shackles",
    name: "Dark Shackles",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    // Strength loss lasts only until end of turn: the matching strength_down (also
    // negative) restores it during end-of-turn upkeep.
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "strength", amount: -9, to: "enemy" },
      { kind: "applyPower", power: "strength_down", amount: -9, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "strength", amount: -15, to: "enemy" },
        { kind: "applyPower", power: "strength_down", amount: -15, to: "enemy" },
      ],
    },
  },
  {
    id: "dramatic_entrance",
    name: "Dramatic Entrance",
    character: "neutral",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "all_enemies",
    innate: true,
    exhaust: true,
    effects: [{ kind: "damage", amount: 8 }],
    upgrade: { effects: [{ kind: "damage", amount: 12 }] },
  },
  {
    id: "finesse",
    name: "Finesse",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [
      { kind: "block", amount: 2 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 4 },
        { kind: "draw", amount: 1 },
      ],
    },
  },
  {
    id: "flash_of_steel",
    name: "Flash of Steel",
    character: "neutral",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 3 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 6 },
        { kind: "draw", amount: 1 },
      ],
    },
  },
  {
    id: "good_instincts",
    name: "Good Instincts",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    effects: [{ kind: "block", amount: 6 }],
    upgrade: { effects: [{ kind: "block", amount: 9 }] },
  },
  {
    id: "master_of_strategy",
    name: "Master of Strategy",
    character: "neutral",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "self",
    exhaust: true,
    effects: [{ kind: "draw", amount: 3 }],
    upgrade: { effects: [{ kind: "draw", amount: 4 }] },
  },
  {
    id: "panacea",
    name: "Panacea",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    exhaust: true,
    effects: [{ kind: "applyPower", power: "artifact", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "artifact", amount: 2, to: "self" }] },
  },
  {
    id: "apparition",
    name: "Apparition",
    character: "neutral",
    type: "skill",
    rarity: "special",
    cost: 1,
    target: "self",
    ethereal: true,
    effects: [{ kind: "applyPower", power: "intangible", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "intangible", amount: 1, to: "self" }] },
  },
  {
    id: "swift_strike",
    name: "Swift Strike",
    character: "neutral",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "damage", amount: 7 }],
    upgrade: { effects: [{ kind: "damage", amount: 10 }] },
  },
  {
    id: "trip",
    name: "Trip",
    character: "neutral",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" }],
    upgrade: { effects: [{ kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" }] },
  },
  {
    id: "shiv",
    name: "Shiv",
    character: "neutral",
    type: "attack",
    rarity: "special",
    cost: 0,
    target: "enemy",
    exhaust: true,
    effects: [{ kind: "damage", amount: 4 }],
    upgrade: { effects: [{ kind: "damage", amount: 6 }] },
  },
  {
    id: "apotheosis",
    name: "Apotheosis",
    character: "neutral",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "self",
    exhaust: true,
    effects: [{ kind: "upgradeAllCards" }],
    upgrade: { cost: 1, effects: [{ kind: "upgradeAllCards" }] },
  },
  {
    id: "soul",
    name: "Soul",
    character: "neutral",
    type: "skill",
    rarity: "special",
    cost: 0,
    target: "self",
    token: true,
    exhaust: true,
    // Necrobinder token: drawn 2, then Exhausts (synergy cards react to it).
    effects: [{ kind: "draw", amount: 2 }],
  },
  {
    id: "ascenders_bane",
    name: "Ascender's Bane",
    character: "neutral",
    type: "curse",
    rarity: "special",
    cost: -2,
    target: "none",
    // A curse: unplayable and Ethereal; clutters the hand until it exhausts.
    unplayable: true,
    ethereal: true,
    effects: [],
  },
  {
    id: "clumsy",
    name: "Clumsy",
    character: "neutral",
    type: "curse",
    rarity: "special",
    cost: -2,
    target: "none",
    // A curse: unplayable and Ethereal.
    unplayable: true,
    ethereal: true,
    effects: [],
  },
];
