import type { CardDef } from "@multispire/shared";

// Regent card definitions. Pure functional game data: name, cost, and numeric
// effects. The Regent's mechanics are Star Energy (a persistent second resource,
// granted by Divine Right and by cards, spent by `starCost`) and Forge (which
// grows the Sovereign Blade token's damage). Values mirror Slay the Spire 2.
//
// Cards whose real behavior leans on systems we don't fully simulate yet (random
// card generation, "auto-play from Exhaust", delayed next-turn effects) are
// marked `approx: true` so the UI shows them as not-yet-supported rather than
// playing a wrong approximation.

export const REGENT_CARDS: CardDef[] = [
  // ---- Starter ----
  {
    id: "strike_reg",
    name: "Strike",
    character: "regent",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defend_reg",
    name: "Defend",
    character: "regent",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 5 }],
    upgrade: { effects: [{ kind: "block", amount: 8 }] },
  },
  {
    id: "falling_star",
    name: "Falling Star",
    character: "regent",
    type: "attack",
    rarity: "basic",
    cost: 0,
    starCost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
      ],
    },
  },
  {
    id: "venerate",
    name: "Venerate",
    character: "regent",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "none",
    effects: [{ kind: "gainStars", amount: 2 }],
    upgrade: { effects: [{ kind: "gainStars", amount: 3 }] },
  },

  // ---- Tokens (generated in combat only; never offered in the deckbuilder) ----
  {
    // The Regent's signature weapon: granted to hand the first time you Forge,
    // strikes for the accumulated Forge, then shuffles back into the draw pile.
    id: "sovereign_blade",
    name: "Sovereign Blade",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 2,
    target: "enemy",
    token: true,
    retain: true,
    reshuffleOnPlay: true,
    effects: [{ kind: "sovereignBladeDamage" }],
    upgrade: { cost: 1 },
  },
  {
    id: "minion_strike",
    name: "Minion Strike",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 0,
    target: "enemy",
    token: true,
    exhaust: true,
    effects: [
      { kind: "damage", amount: 6 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 9 },
        { kind: "draw", amount: 1 },
      ],
    },
  },
  {
    id: "dive_bomb",
    name: "Dive Bomb",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 0,
    target: "enemy",
    token: true,
    exhaust: true,
    effects: [{ kind: "damage", amount: 10 }],
  },

  // ---- Commons / Uncommons / Rares ----
  {
    id: "alignment",
    name: "Alignment",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 0,
    starCost: 3,
    target: "none",
    effects: [{ kind: "gainEnergy", amount: 2 }],
  },
  {
    id: "arsenal",
    name: "Arsenal",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "arsenal", amount: 1, to: "self" }],
  },
  {
    id: "astral_pulse",
    name: "Astral Pulse",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    starCost: 3,
    target: "all_enemies",
    effects: [{ kind: "damage", amount: 14 }],
  },
  {
    id: "begone",
    name: "BEGONE!!",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    // The real card lets you choose; we transform a random hand card instead.
    effects: [{ kind: "transformHand", into: "minion_strike", amount: 1 }],
  },
  {
    id: "big_bang",
    name: "Big Bang",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "none",
    exhaust: true,
    effects: [
      { kind: "draw", amount: 1 },
      { kind: "gainEnergy", amount: 1 },
      { kind: "gainStars", amount: 1 },
      { kind: "forge", amount: 5 },
    ],
  },
  {
    id: "black_hole",
    name: "Black Hole",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "black_hole", amount: 3, to: "self" }],
  },
  {
    id: "bulwark",
    name: "Bulwark",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [
      { kind: "block", amount: 13 },
      { kind: "forge", amount: 10 },
    ],
  },
  {
    id: "celestial_might",
    name: "Celestial Might",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6, times: 3 }],
  },
  {
    id: "charge",
    name: "CHARGE!!!",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    effects: [{ kind: "transformDraw", into: "dive_bomb", amount: 2 }],
  },
  {
    id: "child_of_the_stars",
    name: "Child of the Stars",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "child_of_the_stars", amount: 2, to: "self" }],
  },
  {
    id: "cloak_of_stars",
    name: "Cloak of Stars",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 0,
    starCost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 7 }],
  },
  {
    id: "comet",
    name: "Comet",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 0,
    starCost: 5,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 33 },
      { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
    ],
  },
  {
    id: "conqueror",
    name: "Conqueror",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 3 },
      { kind: "doubleForge" },
    ],
  },
  {
    id: "cosmic_indifference",
    name: "Cosmic Indifference",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 6 },
      { kind: "putDiscardOnDraw", amount: 1 },
    ],
  },
  {
    id: "crescent_spear",
    name: "Crescent Spear",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    starCost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6, perStarCard: 2 }],
  },
  {
    id: "crush_under",
    name: "Crush Under",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "applyPower", power: "strength", amount: -1, to: "enemy" },
    ],
  },
  {
    id: "furnace",
    name: "Furnace",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "auto_forge", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "auto_forge", amount: 6, to: "self" }] },
  },

  {
    id: "beat_into_shape",
    name: "Beat into Shape",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 5 },
      { kind: "forge", amount: 5, perOtherAttackThisTurn: 5 },
    ],
  },
  {
    id: "bombardment",
    name: "Bombardment",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "enemy",
    exhaust: true,
    autoPlayFromExhaust: true,
    effects: [{ kind: "damage", amount: 18 }],
  },
  {
    id: "bundle_of_joy",
    name: "Bundle of Joy",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    exhaust: true,
    effects: [{ kind: "addRandomCards", character: "neutral", amount: 3, pile: "hand" }],
  },
  {
    id: "collision_course",
    name: "Collision Course",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 11 },
      { kind: "addCardToPile", cardId: "debris", amount: 1, pile: "hand" },
    ],
  },
  {
    id: "convergence",
    name: "Convergence",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "nextTurnBonus", energy: 1, stars: 1, retainHand: true }],
  },
  {
    id: "crash_landing",
    name: "Crash Landing",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 21 },
      { kind: "fillHandWith", cardId: "debris" },
    ],
  },
  {
    id: "decisions_decisions",
    name: "Decisions, Decisions",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 0,
    starCost: 6,
    target: "none",
    exhaust: true,
    effects: [
      { kind: "draw", amount: 3 },
      { kind: "replayChosenSkill", times: 3 },
    ],
  },

  // ---- Status token (generated by Collision Course / Crash Landing) ----
  {
    // Debris clogs your hand for a turn, then Exhausts (Ethereal). Unplayable.
    id: "debris",
    name: "Debris",
    character: "regent",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    token: true,
    unplayable: true,
    ethereal: true,
    effects: [],
  },
];
