import type { CardDef } from "@multispire/shared";

// Regent card definitions. Pure functional game data: name, cost, and numeric
// effects. The Regent's mechanics are Star Energy (a persistent second resource,
// granted by Divine Right and by cards, spent by `starCost`) and Forge (which
// grows the Sovereign Blade token's damage). Values mirror Slay the Spire 2.
//
// Cards whose real behavior leans on systems we don't fully simulate yet
// (cost-changes-on-draw, X-cost scaling, discovery/choose-1-of-3, multiplayer-only
// effects, play-from-draw-pile triggers) are marked `approx: true` so the UI shows
// them as not-yet-supported rather than playing a wrong approximation.

export const REGENT_CARDS: CardDef[] = [
  // ---- Starter / Basic ----
  {
    id: "strike_reg",
    name: "Strike",
    character: "regent",
    type: "attack",
    rarity: "basic",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "defend_reg",
    name: "Defend",
    character: "regent",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 5 }],
    upgrade: { effects: [{ kind: "block", amount: 8 }] },
  },
  {
    id: "falling_star",
    name: "Falling Star",
    character: "regent",
    type: "attack",
    rarity: "basic",
    cost: 0,
    starCost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 12 },
        { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
      ],
    },
  },
  {
    id: "venerate",
    name: "Venerate",
    character: "regent",
    type: "skill",
    rarity: "basic",
    cost: 1,
    target: "none",
    effects: [{ kind: "gainStars", amount: 2 }],
    upgrade: { effects: [{ kind: "gainStars", amount: 3 }] },
  },

  // ---- Tokens (generated in combat only; never offered in the deckbuilder) ----
  {
    // The Regent's signature weapon: granted to hand the first time you Forge,
    // strikes for the accumulated Forge, then shuffles back into the draw pile.
    id: "sovereign_blade",
    name: "Sovereign Blade",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 2,
    target: "enemy",
    token: true,
    retain: true,
    reshuffleOnPlay: true,
    effects: [{ kind: "sovereignBladeDamage" }],
    upgrade: { cost: 1 },
  },
  {
    id: "minion_strike",
    name: "Minion Strike",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 0,
    target: "enemy",
    token: true,
    exhaust: true,
    effects: [
      { kind: "damage", amount: 6 },
      { kind: "draw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 9 },
        { kind: "draw", amount: 1 },
      ],
    },
  },
  {
    id: "dive_bomb",
    name: "Dive Bomb",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 0,
    target: "enemy",
    token: true,
    exhaust: true,
    effects: [{ kind: "damage", amount: 10 }],
  },
  {
    // Debris clogs your hand for a turn, then Exhausts (Ethereal). Unplayable.
    id: "debris",
    name: "Debris",
    character: "regent",
    type: "status",
    rarity: "special",
    cost: -2,
    target: "none",
    token: true,
    unplayable: true,
    ethereal: true,
    effects: [],
  },

  // ---- Commons ----
  {
    id: "astral_pulse",
    name: "Astral Pulse",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 0,
    starCost: 3,
    target: "all_enemies",
    effects: [{ kind: "damage", amount: 14 }],
    upgrade: { effects: [{ kind: "damage", amount: 18 }] },
  },
  {
    id: "begone",
    name: "BEGONE!!",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "none",
    // The real card lets you choose; we transform a random hand card instead.
    effects: [{ kind: "transformHand", into: "minion_strike", amount: 1 }],
  },
  {
    id: "celestial_might",
    name: "Celestial Might",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6, times: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 6, times: 4 }] },
  },
  {
    id: "cloak_of_stars",
    name: "Cloak of Stars",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 0,
    starCost: 1,
    target: "self",
    effects: [{ kind: "block", amount: 7 }],
    upgrade: { effects: [{ kind: "block", amount: 10 }] },
  },
  {
    id: "collision_course",
    name: "Collision Course",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 11 },
      { kind: "addCardToPile", cardId: "debris", amount: 1, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 15 },
        { kind: "addCardToPile", cardId: "debris", amount: 1, pile: "hand" },
      ],
    },
  },
  {
    id: "cosmic_indifference",
    name: "Cosmic Indifference",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 6 },
      { kind: "putDiscardOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 9 },
        { kind: "putDiscardOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "crescent_spear",
    name: "Crescent Spear",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    starCost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 6, perStarCard: 2 }],
    upgrade: { effects: [{ kind: "damage", amount: 6, perStarCard: 3 }] },
  },
  {
    id: "crush_under",
    name: "Crush Under",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "applyPower", power: "strength", amount: -1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 8 },
        { kind: "applyPower", power: "strength", amount: -2, to: "enemy" },
      ],
    },
  },
  {
    id: "gather_light",
    name: "Gather Light",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 8 },
      { kind: "gainStars", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 11 },
        { kind: "gainStars", amount: 1 },
      ],
    },
  },
  {
    id: "glitterstream",
    name: "Glitterstream",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 2,
    target: "self",
    effects: [
      { kind: "block", amount: 11 },
      { kind: "nextTurnBonus", block: 5 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 13 },
        { kind: "nextTurnBonus", block: 7 },
      ],
    },
  },
  {
    id: "glow",
    name: "Glow",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "gainStars", amount: 1 },
      { kind: "draw", amount: 1 },
      { kind: "nextTurnBonus", draw: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "gainStars", amount: 2 },
        { kind: "draw", amount: 1 },
        { kind: "nextTurnBonus", draw: 1 },
      ],
    },
  },
  {
    id: "guiding_star",
    name: "Guiding Star",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    starCost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 12 },
      { kind: "draw", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 13 },
        { kind: "draw", amount: 3 },
      ],
    },
  },
  {
    id: "hidden_cache",
    name: "Hidden Cache",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "gainStars", amount: 1 },
      { kind: "nextTurnBonus", stars: 3 },
    ],
    upgrade: {
      effects: [
        { kind: "gainStars", amount: 1 },
        { kind: "nextTurnBonus", stars: 4 },
      ],
    },
  },
  {
    id: "know_thy_place",
    name: "Know Thy Place",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "enemy",
    exhaust: true,
    effects: [
      { kind: "applyPower", power: "weak", amount: 1, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 1, to: "enemy" },
    ],
    // Upgrade no longer Exhausts.
    upgrade: { exhaust: false },
  },
  {
    id: "patter",
    name: "Patter",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 9 },
      { kind: "applyPower", power: "vigor", amount: 2, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 11 },
        { kind: "applyPower", power: "vigor", amount: 3, to: "self" },
      ],
    },
  },
  {
    id: "photon_cut",
    name: "Photon Cut",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 10 },
      { kind: "draw", amount: 1 },
      { kind: "putHandOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 13 },
        { kind: "draw", amount: 2 },
        { kind: "putHandOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "refine_blade",
    name: "Refine Blade",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 9 },
      { kind: "nextTurnBonus", energy: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "forge", amount: 13 },
        { kind: "nextTurnBonus", energy: 1 },
      ],
    },
  },
  {
    id: "solar_strike",
    name: "Solar Strike",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "gainStars", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 10 },
        { kind: "gainStars", amount: 2 },
      ],
    },
  },
  {
    id: "spoils_of_battle",
    name: "Spoils of Battle",
    character: "regent",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 5 },
      { kind: "draw", amount: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "forge", amount: 8 },
        { kind: "draw", amount: 2 },
      ],
    },
  },
  {
    id: "wrought_in_war",
    name: "Wrought in War",
    character: "regent",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 7 },
      { kind: "forge", amount: 7 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 9 },
        { kind: "forge", amount: 9 },
      ],
    },
  },

  // ---- Uncommons ----
  {
    id: "alignment",
    name: "Alignment",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    starCost: 3,
    target: "none",
    effects: [{ kind: "gainEnergy", amount: 2 }],
    upgrade: { effects: [{ kind: "gainEnergy", amount: 3 }] },
  },
  {
    id: "black_hole",
    name: "Black Hole",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "black_hole", amount: 3, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "black_hole", amount: 4, to: "self" }] },
  },
  {
    id: "bulwark",
    name: "Bulwark",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [
      { kind: "block", amount: 13 },
      { kind: "forge", amount: 10 },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 16 },
        { kind: "forge", amount: 13 },
      ],
    },
  },
  {
    id: "charge",
    name: "CHARGE!!!",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    effects: [{ kind: "transformDraw", into: "dive_bomb", amount: 2 }],
  },
  {
    id: "child_of_the_stars",
    name: "Child of the Stars",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "child_of_the_stars", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "child_of_the_stars", amount: 3, to: "self" }] },
  },
  {
    id: "conqueror",
    name: "Conqueror",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 3 },
      { kind: "doubleForge" },
    ],
    upgrade: {
      effects: [
        { kind: "forge", amount: 5 },
        { kind: "doubleForge" },
      ],
    },
  },
  {
    id: "convergence",
    name: "Convergence",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "nextTurnBonus", energy: 1, stars: 1, retainHand: true }],
    upgrade: { effects: [{ kind: "nextTurnBonus", energy: 1, stars: 2, retainHand: true }] },
  },
  {
    id: "devastate",
    name: "Devastate",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    starCost: 4,
    target: "enemy",
    effects: [{ kind: "damage", amount: 30 }],
    upgrade: { effects: [{ kind: "damage", amount: 40 }] },
  },
  {
    id: "furnace",
    name: "Furnace",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "auto_forge", amount: 4, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "auto_forge", amount: 6, to: "self" }] },
  },
  {
    id: "gamma_blast",
    name: "Gamma Blast",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    starCost: 3,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 13 },
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 18 },
        { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "glimmer",
    name: "Glimmer",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "draw", amount: 3 },
      { kind: "putHandOnDraw", amount: 1 },
    ],
    upgrade: {
      effects: [
        { kind: "draw", amount: 4 },
        { kind: "putHandOnDraw", amount: 1 },
      ],
    },
  },
  {
    id: "hegemony",
    name: "Hegemony",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 15 },
      { kind: "nextTurnBonus", energy: 2 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 18 },
        { kind: "nextTurnBonus", energy: 3 },
      ],
    },
  },
  {
    id: "kingly_kick",
    name: "Kingly Kick",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 4,
    target: "enemy",
    // Real card: reduces its own cost by 1 each time you draw it. Not yet modeled.
    approx: true,
    effects: [{ kind: "damage", amount: 27 }],
    upgrade: { effects: [{ kind: "damage", amount: 35 }] },
  },
  {
    id: "kingly_punch",
    name: "Kingly Punch",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    // Real card: grows its damage each time you draw it. Not yet modeled.
    approx: true,
    effects: [{ kind: "damage", amount: 8 }],
    upgrade: { effects: [{ kind: "damage", amount: 10 }] },
  },
  {
    id: "knockout_blow",
    name: "Knockout Blow",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 3,
    target: "enemy",
    effects: [{ kind: "damage", amount: 30, starsOnKill: 5 }],
    upgrade: { effects: [{ kind: "damage", amount: 38, starsOnKill: 5 }] },
  },
  {
    id: "largesse",
    name: "Largesse",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "none",
    // Multiplayer-only: gives an ally a random Colorless card. Not yet modeled.
    approx: true,
    effects: [{ kind: "addRandomCards", character: "neutral", amount: 1, pile: "hand" }],
  },
  {
    id: "lunar_blast",
    name: "Lunar Blast",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    effects: [{ kind: "damage", amount: 0, perSkillThisTurn: 4 }],
    upgrade: { effects: [{ kind: "damage", amount: 0, perSkillThisTurn: 5 }] },
  },
  {
    id: "manifest_authority",
    name: "Manifest Authority",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "block", amount: 7 },
      { kind: "addRandomCards", character: "neutral", amount: 1, pile: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 8 },
        { kind: "addRandomCards", character: "neutral", amount: 1, pile: "hand" },
      ],
    },
  },
  {
    id: "monologue",
    name: "Monologue",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    // This turn, gain 1 temporary Strength each time you play a card.
    effects: [{ kind: "applyPower", power: "monologue", amount: 1, to: "self" }],
    upgrade: { retain: true },
  },
  {
    id: "orbit",
    name: "Orbit",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    // Refund 1 Energy for every 4 Energy you spend this combat.
    effects: [{ kind: "applyPower", power: "orbit", amount: 1, to: "self" }],
    upgrade: { cost: 1 },
  },
  {
    id: "pale_blue_dot",
    name: "Pale Blue Dot",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "pale_blue_dot", amount: 1, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "pale_blue_dot", amount: 2, to: "self" }] },
  },
  {
    id: "parry",
    name: "Parry",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "parry", amount: 10, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "parry", amount: 14, to: "self" }] },
  },
  {
    id: "particle_wall",
    name: "Particle Wall",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    starCost: 2,
    target: "self",
    effects: [
      { kind: "block", amount: 9 },
      { kind: "returnThisCard", to: "hand" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 12 },
        { kind: "returnThisCard", to: "hand" },
      ],
    },
  },
  {
    id: "pillar_of_creation",
    name: "Pillar of Creation",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "pillar_of_creation", amount: 3, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "pillar_of_creation", amount: 4, to: "self" }] },
  },
  {
    id: "prophesize",
    name: "Prophesize",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [{ kind: "draw", amount: 6 }],
    upgrade: { effects: [{ kind: "draw", amount: 9 }] },
  },
  {
    id: "quasar",
    name: "Quasar",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    starCost: 2,
    target: "none",
    // Real card: Discover (choose 1 of 3) a random Colorless card. Not yet modeled;
    // we add a single random one instead.
    approx: true,
    effects: [{ kind: "addRandomCards", character: "neutral", amount: 1, pile: "hand" }],
  },
  {
    id: "radiate",
    name: "Radiate",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    target: "all_enemies",
    effects: [{ kind: "damage", amount: 0, perStarGainedThisTurn: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 0, perStarGainedThisTurn: 4 }] },
  },
  {
    id: "reflect",
    name: "Reflect",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    starCost: 3,
    target: "self",
    // Gain Block, and this turn reflect blocked attack damage back to attackers.
    effects: [
      { kind: "block", amount: 17 },
      { kind: "applyPower", power: "reflect", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "block", amount: 21 },
        { kind: "applyPower", power: "reflect", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "resonance",
    name: "Resonance",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    starCost: 3,
    target: "all_enemies",
    effects: [
      { kind: "applyPower", power: "strength", amount: 1, to: "self" },
      { kind: "applyPower", power: "strength", amount: -1, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "applyPower", power: "strength", amount: 2, to: "self" },
        { kind: "applyPower", power: "strength", amount: -1, to: "enemy" },
      ],
    },
  },
  {
    id: "royal_gamble",
    name: "Royal Gamble",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    starCost: 5,
    target: "none",
    exhaust: true,
    effects: [{ kind: "gainStars", amount: 9 }],
    upgrade: { retain: true },
  },
  {
    id: "shining_strike",
    name: "Shining Strike",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 8 },
      { kind: "gainStars", amount: 2 },
      { kind: "returnThisCard", to: "draw" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 11 },
        { kind: "gainStars", amount: 2 },
        { kind: "returnThisCard", to: "draw" },
      ],
    },
  },
  {
    id: "spectrum_shift",
    name: "Spectrum Shift",
    character: "regent",
    type: "power",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    effects: [{ kind: "applyPower", power: "spectrum_shift", amount: 1, to: "self" }],
    upgrade: { cost: 1 },
  },
  {
    id: "stardust",
    name: "Stardust",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 0,
    // starCost -1: spend ALL Star Energy; deal damage to a random enemy that many times.
    starCost: -1,
    target: "enemy",
    effects: [{ kind: "damagePerX", amount: 5, randomTarget: true }],
    upgrade: { effects: [{ kind: "damagePerX", amount: 7, randomTarget: true }] },
  },
  {
    id: "summon_forth",
    name: "Summon Forth",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 8 },
      { kind: "summonBlade" },
    ],
    upgrade: {
      effects: [
        { kind: "forge", amount: 11 },
        { kind: "summonBlade" },
      ],
    },
  },
  {
    id: "supermassive",
    name: "Supermassive",
    character: "regent",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    effects: [{ kind: "damage", amount: 5, perCardCreatedThisCombat: 3 }],
    upgrade: { effects: [{ kind: "damage", amount: 5, perCardCreatedThisCombat: 4 }] },
  },
  {
    id: "terraforming",
    name: "Terraforming",
    character: "regent",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "vigor", amount: 6, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "vigor", amount: 8, to: "self" }] },
  },

  // ---- Rares ----
  {
    id: "arsenal",
    name: "Arsenal",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "arsenal", amount: 1, to: "self" }],
  },
  {
    id: "beat_into_shape",
    name: "Beat into Shape",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 5 },
      { kind: "forge", amount: 5, perOtherAttackThisTurn: 5 },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 7 },
        { kind: "forge", amount: 7, perOtherAttackThisTurn: 7 },
      ],
    },
  },
  {
    id: "big_bang",
    name: "Big Bang",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "none",
    exhaust: true,
    effects: [
      { kind: "draw", amount: 1 },
      { kind: "gainEnergy", amount: 1 },
      { kind: "gainStars", amount: 1 },
      { kind: "forge", amount: 5 },
    ],
  },
  {
    id: "bombardment",
    name: "Bombardment",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "enemy",
    exhaust: true,
    autoPlayFromExhaust: true,
    effects: [{ kind: "damage", amount: 18 }],
    upgrade: { effects: [{ kind: "damage", amount: 24 }] },
  },
  {
    id: "bundle_of_joy",
    name: "Bundle of Joy",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "none",
    exhaust: true,
    effects: [{ kind: "addRandomCards", character: "neutral", amount: 3, pile: "hand" }],
    upgrade: { effects: [{ kind: "addRandomCards", character: "neutral", amount: 4, pile: "hand" }] },
  },
  {
    id: "comet",
    name: "Comet",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 0,
    starCost: 5,
    target: "enemy",
    effects: [
      { kind: "damage", amount: 33 },
      { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 44 },
        { kind: "applyPower", power: "weak", amount: 3, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 3, to: "enemy" },
      ],
    },
  },
  {
    id: "crash_landing",
    name: "Crash Landing",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 21 },
      { kind: "fillHandWith", cardId: "debris" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 26 },
        { kind: "fillHandWith", cardId: "debris" },
      ],
    },
  },
  {
    id: "decisions_decisions",
    name: "Decisions, Decisions",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 0,
    starCost: 6,
    target: "none",
    exhaust: true,
    effects: [
      { kind: "draw", amount: 3 },
      { kind: "replayChosenSkill", times: 3 },
    ],
    upgrade: {
      effects: [
        { kind: "draw", amount: 5 },
        { kind: "replayChosenSkill", times: 3 },
      ],
    },
  },
  {
    id: "dying_star",
    name: "Dying Star",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 1,
    starCost: 3,
    target: "all_enemies",
    ethereal: true,
    effects: [
      { kind: "damage", amount: 9 },
      { kind: "applyPower", power: "strength", amount: -9, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 11 },
        { kind: "applyPower", power: "strength", amount: -11, to: "enemy" },
      ],
    },
  },
  {
    id: "foregone_conclusion",
    name: "Foregone Conclusion",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    // Real card pulls specific cards from the draw pile; approximated as next-turn draw.
    effects: [{ kind: "nextTurnBonus", draw: 2 }],
    upgrade: { effects: [{ kind: "nextTurnBonus", draw: 3 }] },
  },
  {
    id: "guards",
    name: "GUARDS!!!",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "none",
    exhaust: true,
    // Real card: transform any number of hand cards into Minion Sacrifice. Not yet modeled.
    approx: true,
    effects: [{ kind: "unimplemented", note: "Transform hand cards into Minion Sacrifice" }],
  },
  {
    id: "genesis",
    name: "Genesis",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 2,
    target: "self",
    effects: [{ kind: "applyPower", power: "genesis", amount: 2, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "genesis", amount: 3, to: "self" }] },
  },
  {
    id: "hammer_time",
    name: "Hammer Time",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 2,
    target: "self",
    // Multiplayer-only: allies Forge whenever you Forge. Not yet modeled.
    approx: true,
    effects: [{ kind: "unimplemented", note: "Allies Forge whenever you Forge" }],
    upgrade: { cost: 1 },
  },
  {
    id: "heavenly_drill",
    name: "Heavenly Drill",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: "X",
    target: "enemy",
    // Deal damage X times, where X is the Energy spent; X is doubled if it's 4+.
    effects: [{ kind: "damagePerX", amount: 8, doubleAt: 4 }],
    upgrade: { effects: [{ kind: "damagePerX", amount: 10, doubleAt: 4 }] },
  },
  {
    id: "heirloom_hammer",
    name: "Heirloom Hammer",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    // Deal 20 damage and add a copy of a chosen Colorless card in your hand.
    effects: [
      { kind: "damage", amount: 20 },
      { kind: "duplicateChosen", amount: 1, colorlessOnly: true },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 25 },
        { kind: "duplicateChosen", amount: 1, colorlessOnly: true },
      ],
    },
  },
  {
    id: "i_am_invincible",
    name: "I Am Invincible",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    // Real card: auto-plays from the top of the draw pile at end of turn. Not yet modeled.
    approx: true,
    effects: [{ kind: "block", amount: 10 }],
    upgrade: { effects: [{ kind: "block", amount: 13 }] },
  },
  {
    id: "make_it_so",
    name: "Make It So",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 0,
    target: "enemy",
    // Deal damage. Returns to your hand whenever you play your 3rd Skill in a turn
    // (handled in the engine's card-play hook).
    effects: [{ kind: "damage", amount: 6 }],
    upgrade: { effects: [{ kind: "damage", amount: 9 }] },
  },
  {
    id: "monarchs_gaze",
    name: "Monarch's Gaze",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    effects: [{ kind: "applyPower", power: "monarchs_gaze", amount: 1, to: "self" }],
    upgrade: { cost: 2 },
  },
  {
    id: "neutron_aegis",
    name: "Neutron Aegis",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    starCost: 5,
    target: "self",
    effects: [{ kind: "applyPower", power: "plated_armor", amount: 8, to: "self" }],
    upgrade: { effects: [{ kind: "applyPower", power: "plated_armor", amount: 11, to: "self" }] },
  },
  {
    id: "royalties",
    name: "Royalties",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    // Grants Gold at end of combat — no effect in a PvP battle. Not modeled.
    approx: true,
    effects: [{ kind: "unimplemented", note: "Gain Gold at end of combat" }],
  },
  {
    id: "seeking_edge",
    name: "Seeking Edge",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [
      { kind: "forge", amount: 7 },
      { kind: "applyPower", power: "seeking_edge", amount: 1, to: "self" },
    ],
    upgrade: {
      effects: [
        { kind: "forge", amount: 11 },
        { kind: "applyPower", power: "seeking_edge", amount: 1, to: "self" },
      ],
    },
  },
  {
    id: "seven_stars",
    name: "Seven Stars",
    character: "regent",
    type: "attack",
    rarity: "rare",
    cost: 2,
    starCost: 7,
    target: "all_enemies",
    effects: [{ kind: "damage", amount: 7, times: 7 }],
    upgrade: { cost: 1 },
  },
  {
    id: "sword_sage",
    name: "Sword Sage",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 2,
    target: "self",
    effects: [{ kind: "applyPower", power: "sword_sage", amount: 1, to: "self" }],
    upgrade: { cost: 1 },
  },
  {
    id: "the_smith",
    name: "The Smith",
    character: "regent",
    type: "skill",
    rarity: "rare",
    cost: 1,
    starCost: 4,
    target: "self",
    effects: [{ kind: "forge", amount: 30 }],
    upgrade: { effects: [{ kind: "forge", amount: 40 }] },
  },
  {
    id: "tyranny",
    name: "Tyranny",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 1,
    target: "self",
    effects: [{ kind: "applyPower", power: "tyranny", amount: 1, to: "self" }],
  },
  {
    id: "void_form",
    name: "Void Form",
    character: "regent",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    // The first 2 cards you play each turn cost 0.
    effects: [{ kind: "applyPower", power: "void_form", amount: 2, to: "self" }],
  },

  // ---- Ancients ----
  {
    id: "meteor_shower",
    name: "Meteor Shower",
    character: "regent",
    type: "attack",
    rarity: "special",
    cost: 0,
    starCost: 2,
    target: "all_enemies",
    effects: [
      { kind: "damage", amount: 14 },
      { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
      { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
    ],
    upgrade: {
      effects: [
        { kind: "damage", amount: 21 },
        { kind: "applyPower", power: "weak", amount: 2, to: "enemy" },
        { kind: "applyPower", power: "vulnerable", amount: 2, to: "enemy" },
      ],
    },
  },
  {
    id: "the_sealed_throne",
    name: "The Sealed Throne",
    character: "regent",
    type: "power",
    rarity: "special",
    cost: 1,
    starCost: 3,
    target: "self",
    effects: [{ kind: "applyPower", power: "sealed_throne", amount: 1, to: "self" }],
  },
];
